name: Build and Release Ghostty

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-4-dev libadwaita-1-dev git dpkg-dev debhelper
        
      - name: Clone Ghostty
        run: |
          git clone https://github.com/ghostty-org/ghostty.git
      
      - name: Download and extract Zig
        run: |
          wget https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz
          tar xvf zig-linux-x86_64-0.13.0.tar.xz
      
      - name: Build Ghostty
        run: |
          cd ghostty
          ../zig-linux-x86_64-0.13.0/zig build -Doptimize=ReleaseFast

      - name: Get version
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          
      - name: Create Debian package structure
        run: |
          mkdir -p debian-package/DEBIAN
          mkdir -p debian-package/usr/local/bin
          mkdir -p debian-package/usr/share/applications
          mkdir -p debian-package/usr/share/icons/hicolor/16x16/apps
          mkdir -p debian-package/usr/share/icons/hicolor/32x32/apps
          mkdir -p debian-package/usr/share/icons/hicolor/128x128/apps
          mkdir -p debian-package/usr/share/icons/hicolor/256x256/apps
          mkdir -p debian-package/usr/share/icons/hicolor/512x512/apps
          mkdir -p debian-package/usr/share/icons/hicolor/1024x1024/apps
          
          # Copy binary
          cp ghostty/zig-out/bin/ghostty debian-package/usr/local/bin/
          chmod 755 debian-package/usr/local/bin/ghostty
          
          # Copy icons
          cp ghostty/images/icons/icon_16.png debian-package/usr/share/icons/hicolor/16x16/apps/ghostty.png
          cp ghostty/images/icons/icon_32.png debian-package/usr/share/icons/hicolor/32x32/apps/ghostty.png
          cp ghostty/images/icons/icon_128.png debian-package/usr/share/icons/hicolor/128x128/apps/ghostty.png
          cp ghostty/images/icons/icon_256.png debian-package/usr/share/icons/hicolor/256x256/apps/ghostty.png
          cp ghostty/images/icons/icon_512.png debian-package/usr/share/icons/hicolor/512x512/apps/ghostty.png
          cp ghostty/images/icons/icon_1024.png debian-package/usr/share/icons/hicolor/1024x1024/apps/ghostty.png
          
          # Create control file
          cat > debian-package/DEBIAN/control << EOF
          Package: ghostty
          Version: ${{ steps.get_version.outputs.version }}
          Section: utils
          Priority: optional
          Architecture: amd64
          Depends: libgtk-4-1, libadwaita-1-0
          Maintainer: Mohamed Elashri <mail@elashri.com>
          Description: Modern Terminal Emulator
           Ghostty is a fast, feature-rich, and cross-platform terminal emulator
           that uses platform-native UI and GPU acceleration.
          EOF
          
          # Create desktop entry
          cat > debian-package/usr/share/applications/ghostty.desktop << EOF
          [Desktop Entry]
          Name=Ghostty
          Comment=Modern Terminal Emulator
          Exec=/usr/local/bin/ghostty
          Terminal=false
          Type=Application
          Categories=System;TerminalEmulator;
          EOF
          
      - name: Build DEB package
        run: |
          dpkg-deb --build debian-package
          mv debian-package.deb ghostty_${{ steps.get_version.outputs.version }}_amd64.deb
          
      - name: Package binary
        run: |
          mkdir -p release
          cp ghostty/zig-out/bin/ghostty release/
          tar czf ghostty-linux-x86_64.tar.gz -C release .
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ghostty-linux-x86_64.tar.gz
            ghostty_${{ steps.get_version.outputs.version }}_amd64.deb
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}