name: Build and Release Ghostty

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-4-dev libadwaita-1-dev git dpkg-dev debhelper
        
      - name: Clone Ghostty
        run: |
          git clone https://github.com/ghostty-org/ghostty.git
      
      - name: Download and extract Zig
        run: |
          wget https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz
          tar xvf zig-linux-x86_64-0.13.0.tar.xz
      
      - name: Build and Install Ghostty
        run: |
          cd ghostty
          # First build without installing for portable binary
          ../zig-linux-x86_64-0.13.0/zig build -Doptimize=ReleaseFast
          # Then build with install for proper package structure
          ../zig-linux-x86_64-0.13.0/zig build -Doptimize=ReleaseFast install -p ../install-root
          
          echo "Checking installed files:"
          find ../install-root -type f

      - name: Get version
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          
      - name: Create Debian package structure
        run: |
          # Create basic structure with proper usr prefix
          mkdir -p debian-package/DEBIAN
          mkdir -p debian-package/usr/bin
          mkdir -p debian-package/usr/share
          
          # Copy files to the correct locations
          cp -r install-root/bin/* debian-package/usr/bin/
          cp -r install-root/share/* debian-package/usr/share/
          
          # Ensure proper permissions
          chmod 755 debian-package/usr/bin/ghostty
          chmod 644 debian-package/usr/share/applications/com.mitchellh.ghostty.desktop
          
          # Create control file
          cat > debian-package/DEBIAN/control << EOF
          Package: ghostty
          Version: ${{ steps.get_version.outputs.version }}
          Section: utils
          Priority: optional
          Architecture: amd64
          Depends: libgtk-4-1, libadwaita-1-0
          Maintainer: Mohamed Elashri <mail@elashri.com>
          Description: Modern Terminal Emulator
           Ghostty is a fast, feature-rich, and cross-platform terminal emulator
           that uses platform-native UI and GPU acceleration.
          EOF
          
          echo "Final package structure:"
          find debian-package -type f
          
      - name: Build DEB package
        run: |
          dpkg-deb --build debian-package
          mv debian-package.deb ghostty_${{ steps.get_version.outputs.version }}_amd64.deb
          
          echo "Checking .deb contents:"
          dpkg -c ghostty_${{ steps.get_version.outputs.version }}_amd64.deb
          
      - name: Package portable binary
        run: |
          mkdir -p release
          cp ghostty/zig-out/bin/ghostty release/
          tar czf ghostty-linux-x86_64.tar.gz -C release .
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ghostty-linux-x86_64.tar.gz
            ghostty_${{ steps.get_version.outputs.version }}_amd64.deb
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}